# Permalinks
permalink:           pretty

# Setup
title:               Gilles Bouyer
tagline:             An elementary Blog
url:                 http://rtl.fr
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Gilles Bouyer
  url:               https://twitter.com/17digits
  email:             gilles.bouyer@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/gillesbouyer

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
